pipeline:
  name: Build CI-Auth
  identifier: Build_CI_Auth_1771842226258
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: Github_connector_1
        repoName: CI-Auth
        build: <+input>
